POST http://localhost:8080/api/product
Content-Type: application/json

{"color": "yellow",
"name":  "banana",
"pieces": 400,
"price": 1.00,
"weight": 0.5,
"department": {
  "id": 1
}}

###
POST http://localhost:8080/api/trolleyCart/addProduct
Content-Type: application/json

{"ilosc": 1,
"productId": 2,
"uzytkownikId": 4}

###
POST http://localhost:8080/api/trolleyCart/buy?userId=4&BillingId=17&shippingId=18


###
DELETE http://localhost:8080/api/employee/10



###
POST http://localhost:8080/user/4/address
Content-Type: application/json

{"city": "Libiaz",
  "addressType": "SHIPPING",
  "street": "dfgg",
  "country": "poland",
  "postalCode": "345-55"
}

###
POST http://localhost:8080/user
Content-Type: application/json

{"surname":"dkdk",
"name": "fgg",
  "email": "fkfk@gmail.com",
  "telephone": "1234567"
}

###
POST http://localhost:8080/api/employee/15/address
Content-Type: application/json

{
"postalCode": "3040",
  "street": "aadfgg",
  "country": "apo",
  "addressType": "RESIDENTIAL",
  "city": "dfgh"
}

###
POST http://localhost:8080/api/address
Content-Type: application/json

{"addressType": "RESIDENTIAL",
"city": "Cracow",
"country": "Poland",
"postalCode": "32-590",
  "street": "Wilcza"
}

###
POST http://localhost:8080/api/employee/address
Content-Type: application/json

{"addressType": "RESIDENTIAL",
  "city": "Cracow",
  "country": "Poland",
  "postalCode": "32-590",
  "street": "Wilcza",
  "employee": {
    "id": 14
  }
}

###
POST http://localhost:8080/api/employee
Content-Type: application/json

{"name":"kasia",
  "pesel": 2345,
  "surname": "dfgg",
  "department": {
    "id": 1
  },
"degree": "JUNIOR",
  "position": {
    "id": 1
  }
}

###
POST http://localhost:8080/user
Content-Type: application/json

{"name":  "ddf",
"surname":  "dfgg"}

###
POST http://localhost:8080/api/trolleyCart/addProduct
Content-Type: application/json

{
  "productId": 2,
  "ilosc": 12,
  "uzytkownikId": 4

}

###
POST http://localhost:8080/api/trolleyCart/buy/1



###
POST http://localhost:8080/unit
Content-Type: application/json

{"city": "Cracow",
"department": {
"id": 1
},
"employee": {"id": 10}}

###
POST http://localhost:8080/api/product
Content-Type: application/json

{"color": "red",
  "name": "tomatto",
  "pieces": 123,
  "price": 12.90,
  "weight": 0.50,
  "department": {
    "id": 2
  }
}

###
POST http://localhost:8080/api/employee
Content-Type: application/json

{"name": "basiaa",
"city": "Katowice",
  "pesel": "29453",
  "surname": "dfgh",
"department":{"id": 1}

}

###
POST http://localhost:8080/department
Content-Type: application/json


{
  "name": "miesny",
  "postalCode": "34-000",
  "city": "Katowice"
}

###


###
POST http://localhost:8080/department
Content-Type: application/json

{
  "name": "remotnowka",
  "postalCode": "34-000",
  "city": "Cracow"
}

###
POST http://localhost:80/api/item
Content-Type: application/json

{}

###
GET http://localhost:8080/api/product
Accept: application/json

###
POST http://localhost:8080/api/product/edit/2
Content-Type: application/json

{
  "name": "apple9",
  "price": 129.890,
  "color": "blue",
  "weight": 42
}


###
DELETE http://localhost:8080/api/product/1
